name: CI/CD Pipeline for Railway with MySQL

on:
  push:
    branches:
      - main  # Déclenche le pipeline sur les pushs vers la branche "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Remplacez par la version de Node.js que vous utilisez

      - name: Install dependencies
        run: npm install  # Installez les dépendances de votre projet

      - name: Build the project
        run: npm run build  # Exécutez la commande de build de votre projet

  test:
    runs-on: ubuntu-latest
    needs: build  # Le job "test" s'exécute après le job "build"

    services:
      db:
        image: mysql:latest  # Utilise l'image MySQL
        env:
          MYSQL_ROOT_PASSWORD: root  # Mot de passe root pour MySQL
          MYSQL_DATABASE: mydb_test  # Nom de la base de données
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost -u root -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL to be ready
        run: sleep 20  # Attendre que MySQL soit prêt (ajustez si nécessaire)

      - name: Run Prisma Migrations
        env:
          DATABASE_URL: "mysql://root:root@localhost:3306/mydb_test"  # URL de connexion à la base de données
        run: npx prisma migrate deploy  # Exécutez les migrations Prisma

      - name: Run tests
        env:
          DATABASE_URL: "mysql://root:root@localhost:3306/mydb_test"  # URL de connexion à la base de données
        run: npm test  # Exécutez vos tests

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Le job "deploy" s'exécute après le job "test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          npx railway up
