name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Assurez-vous que la version de Node.js est correcte

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm test

      - name: Build project
        run: npm run build

      # Installer le nouveau Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # Déployer avec la nouvelle CLI
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up
