

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

  quality-check:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint for code quality
        run: npx eslint ./src/ --fix

  test:
    runs-on: ubuntu-latest
    needs: quality-check

    services:
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost -u root -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL to be ready
        run: sleep 20

      - name: Run Prisma Migrations
        env:
          DATABASE_URL: "mysql://root:root@localhost:3306/mydb_test"
        run: npm run migrate

      - name: Run tests
        env:
          DATABASE_URL: "mysql://root:root@localhost:3306/mydb_test"
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm i -g @railway/cli@3.0.8

      - name: Link to Railway
        run: railway link --environment production 1aa51970-ec42-4eea-a5d8-d8fca528a644
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOK }}

      - name: Deploy to PLI  Railway
        run: railway up --service fd350261-4db7-454b-8bb8-b4fc042a107c
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_KEY }}
     
